    branches:
      - main

  schedule:
    - cron: '*/5 * * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    name: integration-tests (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v1
	@@ -41,9 +41,9 @@ jobs:
      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
      - name: Run script
        run: |
          php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
	@@ -64,6 +64,3 @@ jobs:
          TEST_IMAGE_ID: ${{ secrets.TEST_IMAGE_ID }}
          TEST_SUBNET_ID: ${{ secrets.TEST_SUBNET_ID }}
